# This file stores various settings for your site.
# You can include the values of these fields in markdown, e.g.:
# {{ site.data.settings.name }}

# The main name of your site
name: "One Day. One Book."

# A tagline for your site, often shown with the name
tagline: "Creating African children's books together"

# A description of your site, e.g. for social-media snippets
description: >
  In two separate events on 2 June and 9 June 2018, in Gauteng, 
  teams of volunteer creative professionals will gather to create new children's books 
  in African languages, to be translated, printed for thousands of children, 
  and made freely available online. Everyone is a volunteer on the day, giving our time 
  and talent to get more books to more children.

# The main language of your site. Use the IANA language subtag.
# See https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
# or lookup here: https://r12a.github.io/app-subtags/
language: "en"

# A default image for your site, e.g. for social-media snippets
image: "poster.png"

# The logo for your site, if you have one
logo: "reading.png"

# The final, canonical address of your live site
url: "https://onedayonebook.org"

# Your Google Analytics ID, if you're using Google Analytics
google-analytics-id: "UA-71347024-2"

# Your email address, e.g. for the contact form to use
email: "info@onedayonebook.org"
